#!/usr/bin/env node
// Regenerates the design-sync entry barrel, the componentSrcMap, and the
// per-component doc stubs that carry each component's group.
//
// WHY THIS EXISTS
// Acrivault is a Vite *app*, not a published library: there is no `dist/`
// library entry and no `.d.ts` tree, and `node_modules/acrivault` never exists
// (npm won't self-install). The converter therefore needs two things it can't
// discover on its own:
//   1. `--entry` pointing at a real file inside the repo, so it can walk up to
//      the repo's package.json and set PKG_DIR to the repo root.
//   2. An explicit `componentSrcMap`, because with an --entry override the
//      converter skips synth-entry discovery and looks for exports in a .d.ts
//      tree that this repo doesn't ship.
//
// Run this after adding/removing/renaming anything in src/components/**, then
// re-run the converter. Everything it writes is deterministic.
//
//   node .design-sync/gen-entry.mjs
//
import { readdirSync, writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');

// One canonical group per component, using the section vocabulary from the
// team's own showcase page (src/features/platform/design-system/). The showcase
// reuses primitives across sections (Button appears in five); this picks the
// section each component is *about*, not merely used by.
const GROUPS = {
  Foundations: ['Badge', 'Card', 'Logo', 'ScrollableTable'],
  Layout: ['DensityToggle', 'RoleSwitcher', 'ScreenHeader', 'ThemeToggle'],
  Controls: [
    'Button', 'Checkbox', 'CodeInput', 'Combobox', 'IconButton', 'Input',
    'RadioGroup', 'SegmentedControl', 'Select', 'Slider', 'Switch', 'Textarea',
    'ValidityWindowField',
  ],
  Status: [
    'Avatar', 'CloudGlyph', 'CodeBlock', 'KeyValueList', 'KpiTile',
    'NhiTypeIcon', 'PermissionsSummary', 'ProviderBadge', 'RiskPill',
    'StatusBadge', 'StatusDot', 'Tag',
  ],
  Navigation: [
    'Accordion', 'Breadcrumb', 'CommandPalette', 'ConfirmDialog', 'Dialog',
    'Drawer', 'DropdownMenu', 'Pagination', 'Popover', 'Stepper', 'Tabs',
    'Timeline', 'Tooltip',
  ],
  Feedback: [
    'Banner', 'EmptyState', 'ErrorState', 'InlineAlert', 'ProgressBar',
    'QueryBoundary', 'ScanProgress', 'Skeleton', 'Toaster',
  ],
  Charts: ['ActivityChart', 'BarChart', 'LineChart', 'RadialGraph', 'Sparkline'],
  Filters: ['FilterMenu', 'FilterPill'],
  Auth: [
    'AuthCard', 'Can', 'LegalConsent', 'MfaChallenge', 'MfaEnroll',
    'RegistrationProgress', 'RoleRestricted', 'SsoButton',
  ],
};

const groupOf = {};
for (const [group, names] of Object.entries(GROUPS)) {
  for (const n of names) {
    if (groupOf[n]) throw new Error(`${n} is assigned to two groups: ${groupOf[n]} and ${group}`);
    groupOf[n] = group;
  }
}

// ── discover components on disk ──────────────────────────────────────────────
const DIRS = ['src/components/ui', 'src/components/charts'];
const found = [];
for (const dir of DIRS) {
  for (const f of readdirSync(join(REPO, dir)).sort()) {
    if (!f.endsWith('.tsx') || /\.(test|spec|stories)\./.test(f)) continue;
    found.push({ name: f.replace(/\.tsx$/, ''), path: `${dir}/${f}` });
  }
}

// ── reconcile against the group table; drift must be loud, not silent ────────
const onDisk = new Set(found.map((c) => c.name));
const missing = Object.keys(groupOf).filter((n) => !onDisk.has(n));
const ungrouped = found.filter((c) => !groupOf[c.name]).map((c) => c.name);
if (missing.length) console.error(`! grouped but not on disk (remove from GROUPS): ${missing.join(', ')}`);
if (ungrouped.length) console.error(`! on disk but ungrouped (add to GROUPS): ${ungrouped.join(', ')}`);
if (missing.length || ungrouped.length) process.exit(1);

// ── 1. entry barrel ──────────────────────────────────────────────────────────
const barrel =
  '// GENERATED by .design-sync/gen-entry.mjs — do not edit.\n' +
  '// Re-exports every design-system component so the converter has a single\n' +
  '// entry to bundle. Feature screens under src/features/ are deliberately absent.\n' +
  found.map((c) => `export * from '../${c.path.replace(/\.tsx$/, '')}';`).join('\n') +
  '\n' +
  '// Preview-only context providers (Router + react-query + Tooltip), compiled\n' +
  '// into the bundle so cfg.provider can wrap every card with the same context\n' +
  '// copy the components use. See preview-providers.tsx for why this must live here.\n' +
  "export * from './preview-providers';\n" +
  '// The imperative toast() API + its store, so the Toaster preview can push into\n' +
  '// the SAME store instance the bundled Toaster reads (a preview-local copy would\n' +
  '// be a different store). Non-PascalCase, so neither becomes a component card.\n' +
  "export { toast, useToastStore } from '../src/stores/toast';\n";
writeFileSync(join(HERE, 'entry.ts'), barrel);

// ── 2. componentSrcMap into config.json (preserving every other field) ───────
const cfgPath = join(HERE, 'config.json');
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'));
cfg.componentSrcMap = Object.fromEntries(found.map((c) => [c.name, c.path]));
writeFileSync(cfgPath, JSON.stringify(cfg, null, 2) + '\n');

// ── 3. doc stubs — these carry the group via frontmatter `category` ──────────
// Only the frontmatter is owned by this script. A doc with prose below the
// frontmatter is left alone, so hand-written docs survive regeneration.
const docsDir = join(HERE, 'docs');
mkdirSync(docsDir, { recursive: true });
let created = 0, retitled = 0, kept = 0;
for (const c of found) {
  const file = join(docsDir, `${c.name}.md`);
  const fm = `---\ncategory: ${groupOf[c.name]}\n---\n`;
  if (!existsSync(file)) {
    writeFileSync(file, `${fm}\n`);
    created++;
    continue;
  }
  const cur = readFileSync(file, 'utf8');
  const body = cur.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '');
  const next = fm + body;
  if (next !== cur) { writeFileSync(file, next); retitled++; } else kept++;
}

// ── 4. theme default ─────────────────────────────────────────────────────────
// src/styles/tokens.css puts the surface tokens (--bg, --surface, --text-primary,
// …) behind [data-theme='dark'] / [data-theme='light'], and the density tokens
// behind [data-density='…']. index.html supplies data-theme="dark"
// data-density="comfortable" on <html>, so the running app is always themed —
// but nothing else is. A preview card, or a design the claude.ai/design agent
// builds from this system, has no such attribute, so every one of those tokens
// resolves to nothing: white page, black text, dark component surfaces floating
// on top. tokens.css itself calls dark "(default)"; this file is what actually
// makes that true.
//
// Re-projecting the blocks under :not() keeps both themes selectable — set
// data-theme="light" and the light block still wins — while making dark apply
// when the attribute is simply absent.
const tokensCss = readFileSync(join(REPO, 'src/styles/tokens.css'), 'utf8');
const blockOf = (selector) => {
  const m = new RegExp(`\\[${selector}\\]\\s*\\{([\\s\\S]*?)\\n\\}`).exec(tokensCss);
  if (!m) throw new Error(`could not find [${selector}] block in src/styles/tokens.css`);
  return m[1].replace(/^\n+|\n+$/g, '');
};
const darkBlock = blockOf("data-theme='dark'");
const densityBlock = blockOf("data-density='comfortable'");
const countDecls = (s) => (s.match(/^\s*--/gm) || []).length;

writeFileSync(
  join(HERE, 'theme-default.css'),
  '/* GENERATED by .design-sync/gen-entry.mjs from src/styles/tokens.css — do not edit.\n' +
  ' * Re-run the generator after changing the theme blocks in tokens.css.\n' +
  ' *\n' +
  ' * Applies the dark theme and comfortable density when no data-theme /\n' +
  ' * data-density attribute is present, so components render correctly outside\n' +
  ' * the app shell. Setting the attribute explicitly still wins.\n' +
  ' */\n\n' +
  `:root:not([data-theme]) {\n${darkBlock}\n}\n\n` +
  `:root:not([data-density]) {\n${densityBlock}\n}\n`,
);

console.error(
  `entry.ts: ${found.length} components\n` +
  `componentSrcMap: ${found.length} entries\n` +
  `docs/: ${created} created, ${retitled} frontmatter-updated, ${kept} unchanged\n` +
  `theme-default.css: ${countDecls(darkBlock)} dark + ${countDecls(densityBlock)} density tokens\n` +
  `groups: ${Object.entries(GROUPS).map(([g, n]) => `${g}=${n.length}`).join(' ')}`,
);
